name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish -o ./publish
      
      
      
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_MAC_KEY }}
        #ARGS: "-rltgoDzvO"
        SOURCE: "publish/"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: root
        TARGET: /var/www/api
        
        
    - name: ssh Upload
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: scp -r publish root@${{ secrets.HOST }}:/var/www/api
        host: ${{ secrets.HOST }}
        username: root
        passphrase: ${{ secrets.SSH_MAC_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_MAC_KEY}}
        



